name: Build and Publish ivanpashkulev.com UI

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    permissions:
      contents: read
      packages: write
    uses: ivanpashkulev/devops/.github/workflows/build-and-publish.yml@main
    secrets:
      DEVOPS_TOKEN: ${{ secrets.DEVOPS_PAT }}